4/20/2022 AM Publish (#4236)
* Update open-wopen.md

Clarify that _O_TEMPORARY sets FILE_SHARE_DELETE.

* Update other pages that mention _O_TEMPORARY effects.

* New article - IDL method wizard

* update after review

* update after review

* Update after review

* Update after review

* Updating - Add property wizard for VS2022

* Updating broken links

* Update after review

* New article - Add an IDL Property

* link updation

* Update after review

* update after review

* update after review

* New article - IDL MFC property wizard

* Broken link fixed

* Broken link fixed

* Update virtual-functions.md

* update for links

* Updating links

* Address cpp-docs 3780 3782 3790 3791 3805

* Attempt correction of table format

* Add documentation for compiler error C2956 and update error text (#4176)

* Add documentation for compiler error C2956 and update error text

* Add TOC entry

* Update for grammar and my own comprehension.

Sometimes, you just get carried away. This version could use some simplification.

* Simplify.

Address remarks, attempt simplification.
Acrolinx all the things.

* More updates per review

Co-authored-by: Colin Robertson <corob@microsoft.com>

* Address cpp-docs 3816

* Address non-blocking issues from 4207

* fix for sample program.

* edits

* edit pass. Move to ide location

* minor edit

* fix link

* Final update

* final update

* final update

* resolving blocking issue

* resolving blocking issue

* ToC update for new article

* ToC update

* link update

* Correct inconsistent formatting for the `_O_EXCL` constant in the docs for the open functions

* Update c28195.md

* Update in alt-text

* Update in alt-text

* Final Update- See also section

* edit pass

* edit pass

* more cleanup

* typo

* small edit

* Final update

* edit pass

* edit pass

* formatting for scannability

* acrolinx

* one more try at spacing

* final update

* VMCS -> VMXON

According to the intel IA32 development manual (Volume 3 C3 23.7):

"Before executing VMXON, software should allocate a naturally aligned 4-KByte region of memory that a logical
processor may use to support VMX operation. This region is called the VMXON region."

* edit and add links

* fix links

* add code example

* click->tick

* Update date, link to Intel docs

* Another go at updating the description

* Fix stray double-quote

* Address issue in DD PR 1393452

* add /interface and /internal-partition - draft (#4227)

* add /interface and /internal-partition - draft

* add example

* fix formatting

* update text regarding example

* tech review

* link updates

* fix switch name and link

* edits

* reorder version info

* cleanup

* add /tp flag

* fix command line

Co-authored-by: TylerMSFT <Tyler.Whitney@microsoft.com>

* Update os-ot-favor-small-code-favor-fast-code.md

Change "minimize or maximize size" to "minimize size or maximize speed"

* Expand into a whole SEO-friendly sentence

* Clarify when _matherr will be invoked (#4230)

Customer here https://developercommunity.visualstudio.com/t/_matherr-example-does-not-work-for-me/1676341#T-ND10016474 expressed confusion over when _matherr is called. This change points out that the only setting that will enable/disable this is the presence of _matherr, but it will not be triggered when using intrinsics.

* acrolinx and other fixes

* fix typo

* more code escape

* another code escape

* better formatting for retval possibilities

* fix backslashes

* incorp feedback

* SEO work (#4234)

* SEO work

* acrolinx

Co-authored-by: TylerMSFT <Tyler.Whitney@microsoft.com>

Co-authored-by: Steve Wishnousky <stwish@microsoft.com>
Co-authored-by: rachana-satao <83084319+rachana-satao@users.noreply.github.com>
Co-authored-by: opbld15 <opbld15@microsoft.com>
Co-authored-by: Colin Robertson <corob@microsoft.com>
Co-authored-by: opbld16 <opbld16@microsoft.com>
Co-authored-by: opbld17 <opbld17@microsoft.com>
Co-authored-by: atikmapari <31974726+atikmapari@users.noreply.github.com>
Co-authored-by: PRMerger19 <prmrgr19@microsoft.com>
Co-authored-by: Ming Ho <94572161+homing1@users.noreply.github.com>
Co-authored-by: PRMerger5 <prmergr5@microsoft.com>
Co-authored-by: Regan Downer <97987445+v-regandowner@users.noreply.github.com>
Co-authored-by: Jonathan Emmett <joemmett@microsoft.com>
Co-authored-by: Tamara K <93546702+tamarakhader@users.noreply.github.com>
Co-authored-by: TylerMSFT <Tyler.Whitney@microsoft.com>
Co-authored-by: PRMerger17 <prmrgr17@microsoft.com>
Co-authored-by: Paula Miller <v-paulmi@microsoft.com>
Co-authored-by: Martin Storsjö <martin@martin.st>
Co-authored-by: Sunny Chatterjee <sunnych@microsoft.com>
Co-authored-by: Tyler Whitney <TylerMSFT@users.noreply.github.com>
Co-authored-by: Colin Cooper <72402153+v-ccolin@users.noreply.github.com>
Co-authored-by: krispy <monstertyo@gmail.com>
Co-authored-by: PRMerger8 <prmrgr8@microsoft.com>
Co-authored-by: PRMerger10 <prmrgr10@microsoft.com>
Co-authored-by: Tech Stuff <103606018+teknixstuff@users.noreply.github.com>
Co-authored-by: Dennis Rea <v-denrea@microsoft.com>